#  PART1:Using Tools

## 第一部分：工具使用（NumPy + SciPy + PyTorch）

### 1.1 NumPy 常用操作

#### 1.1.1 数组创建

In [5]:
import numpy as np

# 创建全零/全一数组
zeros_arr = np.zeros((3, 4))        # 3行4列全零矩阵
ones_arr = np.ones((2, 3))          # 2行3列全一矩阵

# 创建等差/等分数列
arange_arr = np.arange(0, 10, 2)    # [0, 2, 4, 6, 8]，步长为2
linspace_arr = np.linspace(0, 1, 5) # [0, 0.25, 0.5, 0.75, 1.0]，5个等分点

# 随机数
rand_arr = np.random.rand(3, 3)     # [0,1)均匀分布，3x3
randn_arr = np.random.randn(3, 3)   # 标准正态分布，3x3
randint_arr = np.random.randint(0, 10, size=(3, 3))  # [0,10)整数

# 从列表创建
arr = np.array([[1, 2, 3], [4, 5, 6]])  # 2x3数组
print(f"形状: {arr.shape}, 数据类型: {arr.dtype}")

形状: (2, 3), 数据类型: int32


#### 1.1.2 数组运算

In [6]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# 逐元素运算（对应位置相加/相乘）
print(a + b)       # 逐元素加法
print(a * b)       # 逐元素乘法（不是矩阵乘法！）

# 矩阵乘法（线性代数中的矩阵相乘）
print(a @ b)                 # 推荐写法：矩阵乘法
print(np.dot(a, b))          # 等价写法
print(np.matmul(a, b))       # 等价写法

# 广播机制：不同形状数组运算时自动扩展
c = np.array([1, 2])        # shape (2,)
print(a + c)                 # c自动广播为[[1,2],[1,2]]再相加

# 标量运算
print(a * 2)                 # 每个元素乘2
print(np.exp(a))             # 每个元素取e的幂

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[2 4]
 [4 6]]
[[2 4]
 [6 8]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


#### 1.1.3 索引与切片

In [7]:
import numpy as np

arr = np.arange(24).reshape(4, 6)  # 4x6矩阵

# 基本切片：取第1-2行，第2-4列
print(arr[1:3, 2:5])

# 花式索引（用数组指定多个下标）
rows = np.array([0, 2, 3])         # 取第0、2、3行
print(arr[rows])

# 布尔索引（按条件筛选）
mask = arr > 15                     # 大于15的位置为True
print(arr[mask])                    # 输出所有大于15的元素

# 条件赋值
arr[arr < 10] = 0                   # 小于10的元素全部置为0
print(arr)

[[ 8  9 10]
 [14 15 16]]
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[16 17 18 19 20 21 22 23]
[[ 0  0  0  0  0  0]
 [ 0  0  0  0 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


#### 1.1.4 形状操作

In [8]:
import numpy as np

arr = np.arange(12)  # [0,1,...,11]

# reshape：改变形状（不改变数据）
print(arr.reshape(3, 4))    # 变为3x4
print(arr.reshape(2, -1))   # -1表示自动推算，变为2x6

# transpose：转置
mat = np.arange(6).reshape(2, 3)
print(mat.T)                 # 转置，3x2

# concatenate：沿指定轴拼接
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.concatenate([a, b], axis=0))  # 纵向拼接，4x2
print(np.concatenate([a, b], axis=1))  # 横向拼接，2x4

# stack：新增一个维度堆叠
print(np.stack([a, b]))              # shape (2,2,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[0 3]
 [1 4]
 [2 5]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### 1.1.5 统计函数

In [9]:
import numpy as np

arr = np.random.randn(5, 4)  # 5x4随机矩阵

# 基础统计
print(f"均值: {arr.mean()}")           # 全局均值
print(f"按列均值: {arr.mean(axis=0)}")  # 每列的均值
print(f"标准差: {arr.std()}")           # 全局标准差
print(f"求和: {arr.sum()}")             # 全局求和

# argmax/argmin：找最大/最小值的索引
print(f"全局最大值索引: {arr.argmax()}")        # 展平后的索引
print(f"每行最大值索引: {arr.argmax(axis=1)}")   # 每行中最大值的列索引

# cumsum：累积求和
print(f"累积和: {np.array([1,2,3,4]).cumsum()}")  # [1,3,6,10]

均值: -0.032657432475418316
按列均值: [-0.66041481 -0.03105471  0.35995515  0.20088463]
标准差: 0.6550715703518033
求和: -0.6531486495083664
全局最大值索引: 18
每行最大值索引: [2 2 3 0 2]
累积和: [ 1  3  6 10]


#### 1.1.6 经典案例：NumPy手写线性回归

In [10]:
import numpy as np

# ====== 生成模拟数据：y = 3x + 2 + 噪声 ======
np.random.seed(42)
X = 2 * np.random.rand(100, 1)           # 100个样本，1个特征
y = 3 * X.ravel() + 2 + np.random.randn(100) * 0.5  # 加入噪声

# ====== 方法1：正规方程 w = (X^T X)^{-1} X^T y ======
X_b = np.c_[np.ones((100, 1)), X]        # 添加偏置列 [1, x]
w_normal = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y
print(f"正规方程: 截距={w_normal[0]:.3f}, 斜率={w_normal[1]:.3f}")

# ====== 方法2：梯度下降 ======
lr = 0.1                                  # 学习率
n_epochs = 200                            # 迭代次数
w = np.random.randn(2)                    # 随机初始化权重 [截距, 斜率]

for epoch in range(n_epochs):
    y_pred = X_b @ w                      # 前向传播：预测值
    error = y_pred - y                    # 预测误差
    grad = (2 / 100) * X_b.T @ error     # 梯度（MSE的导数）
    w -= lr * grad                        # 参数更新

print(f"梯度下降: 截距={w[0]:.3f}, 斜率={w[1]:.3f}")

正规方程: 截距=2.108, 斜率=2.885
梯度下降: 截距=2.107, 斜率=2.885


### 1.2 SciPy 常用操作

#### 1.2.1 scipy.optimize（优化与拟合）

In [11]:
import numpy as np
from scipy.optimize import minimize, curve_fit

# ====== 最小化函数 ======
def f(x):
    return (x[0] - 3)**2 + (x[1] - 1)**2  # 最小值在(3,1)

result = minimize(f, x0=[0, 0])            # 从(0,0)开始搜索
print(f"最小值点: {result.x}, 最小值: {result.fun:.4f}")

# ====== 曲线拟合：用curve_fit拟合正弦波 ======
def sine_func(x, A, omega, phi):
    return A * np.sin(omega * x + phi)     # A:振幅, omega:角频率, phi:相位

np.random.seed(42)
x_data = np.linspace(0, 4*np.pi, 50)
y_data = 2.5 * np.sin(1.5 * x_data + 0.3) + np.random.randn(50) * 0.3

popt, pcov = curve_fit(sine_func, x_data, y_data, p0=[2, 1, 0])  # p0:初始猜测
print(f"拟合参数: A={popt[0]:.3f}, omega={popt[1]:.3f}, phi={popt[2]:.3f}")

最小值点: [3.00000007 0.9999999 ], 最小值: 0.0000
拟合参数: A=0.748, omega=0.770, phi=1.614


#### 1.2.2 scipy.stats（统计与假设检验）

In [12]:
import numpy as np
from scipy import stats

# ====== 概率分布 ======
x = np.linspace(-4, 4, 100)
pdf = stats.norm.pdf(x)                    # 概率密度函数
cdf = stats.norm.cdf(0)                    # P(X<=0) = 0.5
print(f"标准正态P(X<=0) = {cdf:.4f}")

# 生成随机样本
samples = stats.norm.rvs(loc=5, scale=2, size=1000)  # 均值5,标准差2
print(f"样本均值: {samples.mean():.2f}, 样本标准差: {samples.std():.2f}")

# ====== 假设检验 ======
np.random.seed(42)
group_a = np.random.normal(70, 10, 30)    # A组成绩
group_b = np.random.normal(75, 10, 30)    # B组成绩

# 独立样本t检验：两组均值是否有显著差异
t_stat, p_value = stats.ttest_ind(group_a, group_b)
print(f"t统计量={t_stat:.3f}, p值={p_value:.4f}")
print(f"结论: {'显著差异' if p_value < 0.05 else '无显著差异'}(alpha=0.05)")

标准正态P(X<=0) = 0.5000
样本均值: 5.09, 样本标准差: 1.96
t统计量=-2.398, p值=0.0197
结论: 显著差异(alpha=0.05)


#### 1.2.3 scipy.linalg（线性代数）

In [13]:
import numpy as np
from scipy import linalg

A = np.array([[4, 2], [1, 3]])

# 矩阵求逆
A_inv = linalg.inv(A)
print(f"逆矩阵:\n{A_inv}")
print(f"验证 A*A_inv = I:\n{A @ A_inv}")

# LU分解：A = P * L * U
P, L, U = linalg.lu(A)
print(f"L:\n{L}\nU:\n{U}")

# 特征值分解
eigenvalues, eigenvectors = linalg.eig(A)
print(f"特征值: {eigenvalues}")

# 解线性方程组 Ax = b
b = np.array([8, 4])
x = linalg.solve(A, b)
print(f"方程组解: x={x}")

逆矩阵:
[[ 0.3 -0.2]
 [-0.1  0.4]]
验证 A*A_inv = I:
[[ 1.00000000e+00  0.00000000e+00]
 [-2.77555756e-17  1.00000000e+00]]
L:
[[1.   0.  ]
 [0.25 1.  ]]
U:
[[4.  2. ]
 [0.  2.5]]
特征值: [5.+0.j 2.+0.j]
方程组解: x=[1.6 0.8]


#### 1.2.4 scipy.sparse（稀疏矩阵）

In [14]:
import numpy as np
from scipy import sparse

# 创建稀疏矩阵（COO格式：坐标存储）
row = np.array([0, 1, 2, 3])
col = np.array([0, 1, 2, 3])
data = np.array([1, 2, 3, 4])
A_sparse = sparse.coo_matrix((data, (row, col)), shape=(4, 4))
print(f"稀疏矩阵(COO):\n{A_sparse.toarray()}")

# 转为CSR格式（适合矩阵运算）
A_csr = A_sparse.tocsr()
print(f"非零元素个数: {A_csr.nnz}")

# 稀疏矩阵运算
b = np.array([1, 1, 1, 1])
x = sparse.linalg.spsolve(A_csr, b)  # 解稀疏方程组
print(f"稀疏方程组解: {x}")

稀疏矩阵(COO):
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
非零元素个数: 4
稀疏方程组解: [1.         0.5        0.33333333 0.25      ]


### 1.3 PyTorch 常用操作（CPU版）

#### 1.3.1 张量创建与运算（与NumPy对比）

In [1]:
import torch
import numpy as np

device = torch.device('cpu')  # 强制使用CPU

# ====== 创建张量 ======
a = torch.zeros(3, 4)                  # 全零，类似np.zeros
b = torch.ones(2, 3)                   # 全一
c = torch.arange(0, 10, 2)             # [0,2,4,6,8]
d = torch.linspace(0, 1, 5)            # [0,0.25,0.5,0.75,1.0]
e = torch.randn(3, 3)                  # 标准正态随机
print(f"张量形状: {e.shape}, 设备: {e.device}")

# ====== NumPy <-> PyTorch 互转 ======
np_arr = np.array([1, 2, 3])
t_from_np = torch.from_numpy(np_arr)   # NumPy -> Tensor（共享内存！）
np_from_t = e.numpy()                   # Tensor -> NumPy

# ====== 张量运算 ======
x = torch.tensor([[1., 2.], [3., 4.]])
y = torch.tensor([[5., 6.], [7., 8.]])
print(x + y)          # 逐元素加
print(x * y)          # 逐元素乘
print(x @ y)          # 矩阵乘法
print(x.T)            # 转置

# ====== 常用函数 ======
print(f"均值: {x.mean()}")
print(f"最大值: {x.max()}")
print(f"argmax: {x.argmax()}")
print(f"reshape: {x.reshape(4)}")

张量形状: torch.Size([3, 3]), 设备: cpu
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[19., 22.],
        [43., 50.]])
tensor([[1., 3.],
        [2., 4.]])
均值: 2.5
最大值: 4.0
argmax: 3
reshape: tensor([1., 2., 3., 4.])


#### 1.3.2 autograd 自动求导

In [2]:
import torch

# ====== 基本自动求导 ======
x = torch.tensor([2.0], requires_grad=True)  # 声明需要求导
y = x**3 + 2*x**2 + 1                        # y = x^3 + 2x^2 + 1
y.backward()                                  # 反向传播，计算梯度
print(f"dy/dx 在x=2处: {x.grad}")             # 3x^2+4x = 12+8 = 20

# ====== 多变量求导 ======
w = torch.tensor([1.0], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)
x = torch.tensor([3.0])
y_pred = w * x + b                           # 线性预测
loss = (y_pred - 5)**2                        # MSE loss，目标值5
loss.backward()
print(f"dloss/dw = {w.grad}")                 # 2*(wx+b-5)*x = 2*(-2)*3 = -12
print(f"dloss/db = {b.grad}")                 # 2*(wx+b-5) = 2*(-2) = -4

# ====== 梯度清零 ======
w.grad.zero_()  # PyTorch不会自动清零，需手动清除
b.grad.zero_()

dy/dx 在x=2处: tensor([20.])
dloss/dw = tensor([-12.])
dloss/db = tensor([-4.])


tensor([0.])

#### 1.3.3 Dataset 与 DataLoader

In [3]:
import torch
from torch.utils.data import Dataset, DataLoader

# ====== 自定义Dataset ======
class MyDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.FloatTensor(X)   # 转为Tensor
        self.y = torch.FloatTensor(y)

    def __len__(self):
        return len(self.X)               # 数据集大小

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]  # 按索引取数据

# ====== 使用DataLoader批量加载 ======
import numpy as np
np.random.seed(42)
X = np.random.randn(200, 5)  # 200个样本，5个特征
y = np.random.randn(200)

dataset = MyDataset(X, y)
loader = DataLoader(dataset, batch_size=32, shuffle=True)  # 每批32个，打乱顺序

for batch_X, batch_y in loader:
    print(f"批次大小: {batch_X.shape}")  # torch.Size([32, 5])或最后一个batch
    break  # 只看第一个batch

批次大小: torch.Size([32, 5])


#### 1.3.4 nn.Module 定义网络

In [4]:
import torch
import torch.nn as nn

# ====== 定义一个两层全连接网络 ======
class SimpleNet(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)  # 第一层
        self.relu = nn.ReLU()                         # 激活函数
        self.fc2 = nn.Linear(hidden_dim, output_dim)  # 第二层

    def forward(self, x):
        x = self.fc1(x)      # 线性变换
        x = self.relu(x)     # 非线性激活
        x = self.fc2(x)      # 输出层
        return x

# ====== 实例化并查看结构 ======
net = SimpleNet(input_dim=5, hidden_dim=16, output_dim=1)
print(net)                                # 打印网络结构
print(f"参数总量: {sum(p.numel() for p in net.parameters())}")

SimpleNet(
  (fc1): Linear(in_features=5, out_features=16, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=16, out_features=1, bias=True)
)
参数总量: 113


#### 1.3.5 训练循环模板

In [5]:
import torch
import torch.nn as nn
import torch.optim as optim

# ====== 标准训练循环5步法 ======
# forward -> loss -> zero_grad -> backward -> step

device = torch.device('cpu')
model = SimpleNet(5, 16, 1).to(device)
criterion = nn.MSELoss()                    # 损失函数
optimizer = optim.SGD(model.parameters(), lr=0.01)  # 优化器

# 模拟训练数据
X_train = torch.randn(100, 5)
y_train = torch.randn(100, 1)

for epoch in range(50):
    # 1. 前向传播
    y_pred = model(X_train)
    # 2. 计算损失
    loss = criterion(y_pred, y_train)
    # 3. 清零梯度（必须在backward之前！）
    optimizer.zero_grad()
    # 4. 反向传播（计算梯度）
    loss.backward()
    # 5. 更新参数
    optimizer.step()

    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1:3d}, Loss: {loss.item():.4f}")

Epoch  10, Loss: 1.1362
Epoch  20, Loss: 1.0954
Epoch  30, Loss: 1.0752
Epoch  40, Loss: 1.0638
Epoch  50, Loss: 1.0563


#### 1.3.6 经典案例：PyTorch手写线性回归（与NumPy版对比）

In [6]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

# ====== 生成数据（与NumPy版相同） ======
np.random.seed(42)
X_np = 2 * np.random.rand(100, 1)
y_np = 3 * X_np.ravel() + 2 + np.random.randn(100) * 0.5

# ====== PyTorch方式 ======
device = torch.device('cpu')
X = torch.FloatTensor(X_np)
y = torch.FloatTensor(y_np).unsqueeze(1)  # 变为(100,1)

# 定义模型：1维输入 -> 1维输出
model = nn.Linear(1, 1).to(device)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

for epoch in range(200):
    y_pred = model(X)               # 前向传播
    loss = criterion(y_pred, y)     # 计算MSE
    optimizer.zero_grad()           # 清零梯度
    loss.backward()                 # 反向传播
    optimizer.step()                # 更新参数

# 提取学习到的参数
w, b = model.weight.item(), model.bias.item()
print(f"PyTorch线性回归: 斜率={w:.3f}, 截距={b:.3f}")
print(f"（真实值: 斜率=3.000, 截距=2.000）")

PyTorch线性回归: 斜率=2.885, 截距=2.108
（真实值: 斜率=3.000, 截距=2.000）
